<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Logic\Providers\FacebookRepository;

class SocialController extends Controller
{
    //
    // protected $facebook;

    // public function __construct()
    // {
    //     $this->facebook = new FacebookRepository();
    // }
    public function hello(){
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/{1063550061106882}/feed
        ?message=Hello Fans!
        &access_token={EAAPHSwuX1sIBAJgDcO0tX5BAfkfADMF7kip4YWg7I8Mklya0BHZBydVFEd92VwU7s3XHsojqUiTpTxDFQLAo89oSlX8YpkGOoM8JgTr0darYnqyba1ZAncG5KNk6jl7Ck2bcrUI3kIZBBJQnnUJQ1BSrBRXzNaW5QUaYb09ECQJ1zjZAejaI1u3KuGSZAaORa2uGhpT5dshwT0ESzLDoI}');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        dd("ok");
    }

    public function redirectToProvider()
    {
        return redirect($this->facebook->redirectTo());
    }

    public function handleProviderCallback()
    {
        if (request('error') == 'access_denied') 
            //handle error

        $accessToken = $this->facebook->handleCallback(); 
        
        //use token to get facebook pages
    }
    
}
